// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfBuvqYyr8HSX8cgP4ip-atrJoXkp_WGM',
    appId: '1:23632118686:web:cf16e318d845faca8c4c8f',
    messagingSenderId: '23632118686',
    projectId: 'trams-app',
    authDomain: 'trams-app.firebaseapp.com',
    storageBucket: 'trams-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHmBjfgkmYy5QxiELA8n_Fh2ONuOy8DEE',
    appId: '1:23632118686:android:9c48f739f3a8139a8c4c8f',
    messagingSenderId: '23632118686',
    projectId: 'trams-app',
    storageBucket: 'trams-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHfpArc-f4n3NwU1LFy6Bpn8vEL_48XII',
    appId: '1:23632118686:ios:4b233cd03c1fc7fa8c4c8f',
    messagingSenderId: '23632118686',
    projectId: 'trams-app',
    storageBucket: 'trams-app.appspot.com',
    iosClientId: '23632118686-hhjbhlnlqj58jkpmi7ajgqh3jlcbjf6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );
}
